name: FearHungerTranslation
version: 1.0.0+1
environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  csv: ^5.0.2
  json_annotation: ^4.8.1
dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1